"""One place that knows the difference between SQLite and PostgreSQL.

Perch runs on a guesthouse owner's own laptop from a single file, and on
Supabase for the same owner's phone.  Those are the same product, so the
ledger, the sync engine and the API are written once and this module absorbs
the dialect differences.

Only what the app actually uses is abstracted — placeholders, auto-generated
ids, upserts, and how a write transaction is opened.  There is no attempt at a
general ORM: the whole point of the design is that the *database* enforces the
double-booking guarantee, and that only survives if the SQL stays legible.
"""

from __future__ import annotations

import re
import sqlite3
from pathlib import Path
from urllib.parse import urlparse

SQLITE = "sqlite"
POSTGRES = "postgres"


def dialect_of(url: str) -> str:
    """Work out which backend a connection string means."""
    text = str(url)
    if text.startswith(("postgres://", "postgresql://", "postgresql+psycopg://")):
        return POSTGRES
    return SQLITE


# ---------------------------------------------------------------------------
# Schema
#
# Written once, with the handful of genuinely dialect-specific pieces left as
# tokens.  A second copy of the schema would drift, and a drifted schema is how
# the invariant that prevents double bookings quietly stops applying on one of
# the two backends.
# ---------------------------------------------------------------------------

TOKENS = {
    SQLITE: {
        "pk": "INTEGER PRIMARY KEY",
        "without_rowid": " WITHOUT ROWID",
    },
    POSTGRES: {
        "pk": "INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY",
        "without_rowid": "",
    },
}

SCHEMA = """
CREATE TABLE IF NOT EXISTS property (
    id              {pk},
    -- The Supabase user who owns this property.  NULL in local single-owner
    -- mode, where the app is only reachable from the machine it runs on.
    owner_id        TEXT,
    name            TEXT    NOT NULL,
    timezone        TEXT    NOT NULL DEFAULT 'UTC',
    currency        TEXT    NOT NULL DEFAULT 'EUR',
    locale          TEXT    NOT NULL DEFAULT 'en',
    hold_last_room  INTEGER NOT NULL DEFAULT 0,
    created_at      TEXT    NOT NULL
);

CREATE INDEX IF NOT EXISTS property_owner ON property (owner_id);

CREATE TABLE IF NOT EXISTS room (
    id              {pk},
    property_id     INTEGER NOT NULL REFERENCES property(id) ON DELETE CASCADE,
    name            TEXT    NOT NULL,
    capacity        INTEGER NOT NULL DEFAULT 2,
    base_rate_cents INTEGER NOT NULL DEFAULT 9000,
    sort_order      INTEGER NOT NULL DEFAULT 0,
    active          INTEGER NOT NULL DEFAULT 1,
    UNIQUE (property_id, name)
);

CREATE TABLE IF NOT EXISTS channel (
    id              {pk},
    property_id     INTEGER NOT NULL REFERENCES property(id) ON DELETE CASCADE,
    room_id         INTEGER REFERENCES room(id) ON DELETE CASCADE,
    kind            TEXT    NOT NULL,
    name            TEXT    NOT NULL,
    tier            TEXT    NOT NULL DEFAULT 'ical' CHECK (tier IN ('ical', 'api')),
    import_url      TEXT,
    export_token    TEXT    UNIQUE,
    inbound_token   TEXT    UNIQUE,
    refresh_minutes INTEGER NOT NULL DEFAULT 60,
    stop_sell_hours INTEGER NOT NULL DEFAULT 0,
    status          TEXT    NOT NULL DEFAULT 'pending',
    status_detail   TEXT,
    last_success_at TEXT,
    enabled         INTEGER NOT NULL DEFAULT 1
);

CREATE TABLE IF NOT EXISTS booking (
    id              {pk},
    property_id     INTEGER NOT NULL REFERENCES property(id) ON DELETE CASCADE,
    room_id         INTEGER NOT NULL REFERENCES room(id) ON DELETE CASCADE,
    channel_id      INTEGER REFERENCES channel(id) ON DELETE SET NULL,
    external_ref    TEXT,
    guest_name      TEXT,
    guest_email     TEXT,
    guest_phone     TEXT,
    guests          INTEGER NOT NULL DEFAULT 1,
    checkin         TEXT    NOT NULL,
    checkout        TEXT    NOT NULL,
    amount_cents    INTEGER,
    currency        TEXT,
    notes           TEXT,
    kind            TEXT    NOT NULL DEFAULT 'stay' CHECK (kind IN ('stay', 'block')),
    status          TEXT    NOT NULL DEFAULT 'confirmed'
                    CHECK (status IN ('confirmed', 'cancelled', 'conflicted')),
    created_at      TEXT    NOT NULL,
    updated_at      TEXT    NOT NULL,
    CHECK (checkout > checkin)
);

CREATE UNIQUE INDEX IF NOT EXISTS booking_external_ref
    ON booking (channel_id, external_ref) WHERE external_ref IS NOT NULL;
CREATE INDEX IF NOT EXISTS booking_stay ON booking (property_id, checkin, checkout);

-- The ledger.  One row per *occupied* room-night; the absence of a row means
-- the night is open.  The primary key is the entire double-booking defence:
-- two reservations for the same room-night cannot both exist, so the second
-- write fails at the storage layer rather than relying on application code
-- remembering to check.  This holds identically on both backends.
CREATE TABLE IF NOT EXISTS room_night (
    room_id     INTEGER NOT NULL REFERENCES room(id) ON DELETE CASCADE,
    night       TEXT    NOT NULL,
    state       TEXT    NOT NULL CHECK (state IN ('sold', 'held', 'closed')),
    booking_id  INTEGER REFERENCES booking(id) ON DELETE CASCADE,
    channel_id  INTEGER REFERENCES channel(id) ON DELETE SET NULL,
    reason      TEXT,
    updated_at  TEXT    NOT NULL,
    PRIMARY KEY (room_id, night)
){without_rowid};

CREATE INDEX IF NOT EXISTS room_night_by_night ON room_night (night);

CREATE TABLE IF NOT EXISTS conflict (
    id              {pk},
    property_id     INTEGER NOT NULL REFERENCES property(id) ON DELETE CASCADE,
    room_id         INTEGER NOT NULL REFERENCES room(id) ON DELETE CASCADE,
    incumbent_id    INTEGER REFERENCES booking(id) ON DELETE CASCADE,
    challenger_id   INTEGER REFERENCES booking(id) ON DELETE CASCADE,
    nights          TEXT    NOT NULL,
    detected_at     TEXT    NOT NULL,
    resolved_at     TEXT,
    resolution      TEXT
);

CREATE TABLE IF NOT EXISTS idempotency (
    key         TEXT PRIMARY KEY,
    booking_id  INTEGER REFERENCES booking(id) ON DELETE CASCADE,
    outcome     TEXT NOT NULL,
    created_at  TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS sync_log (
    id          {pk},
    channel_id  INTEGER REFERENCES channel(id) ON DELETE CASCADE,
    direction   TEXT    NOT NULL,
    status      TEXT    NOT NULL,
    detail      TEXT,
    imported    INTEGER NOT NULL DEFAULT 0,
    cancelled   INTEGER NOT NULL DEFAULT 0,
    conflicts   INTEGER NOT NULL DEFAULT 0,
    at          TEXT    NOT NULL
);

CREATE INDEX IF NOT EXISTS sync_log_recent ON sync_log (at);
"""


def schema_for(dialect: str) -> str:
    return SCHEMA.format(**TOKENS[dialect])


# ---------------------------------------------------------------------------
# Connection wrapper
# ---------------------------------------------------------------------------

_PLACEHOLDER = re.compile(r"\?")


class Database:
    """A thin, deliberately boring wrapper over a DB-API connection.

    Callers write SQLite-flavoured SQL with ``?`` placeholders — the same SQL
    that has always been in this codebase — and this translates where needed.
    """

    def __init__(self, raw, dialect: str):
        self.raw = raw
        self.dialect = dialect
        if dialect == POSTGRES:
            import psycopg

            self.IntegrityError = psycopg.IntegrityError
        else:
            self.IntegrityError = sqlite3.IntegrityError

    # -- statement plumbing ---------------------------------------------------

    def sql(self, statement: str) -> str:
        """Adapt a statement to the backend.

        The only rewrite is the placeholder style.  It is a plain substitution
        because no SQL in this codebase contains a literal ``?`` or ``%``; if
        that ever changes, this is the line that has to become cleverer.
        """
        if self.dialect == POSTGRES:
            return _PLACEHOLDER.sub("%s", statement)
        return statement

    def execute(self, statement: str, params=()):
        return self.raw.execute(self.sql(statement), tuple(params))

    def executemany(self, statement: str, rows):
        rows = list(rows)
        if not rows:
            return _Empty()
        if self.dialect == POSTGRES:
            cur = self.raw.cursor()
            cur.executemany(self.sql(statement), [tuple(r) for r in rows])
            return cur
        return self.raw.executemany(statement, rows)

    def executescript(self, script: str) -> None:
        if self.dialect == POSTGRES:
            self.raw.execute(script)
        else:
            self.raw.executescript(script)

    # -- the operations whose syntax actually differs -------------------------

    def insert(self, table: str, values: dict, *, returning: str | None = "id"):
        """Insert one row and return its generated id.

        SQLite hands back ``lastrowid``; PostgreSQL has no such thing and needs
        ``RETURNING``.  Pass ``returning=None`` for a table whose key the caller
        already supplied (``idempotency`` is keyed on the caller's own key and
        has no id column at all).
        """
        columns = ", ".join(values)
        marks = ", ".join("?" * len(values))
        params = tuple(values.values())
        statement = f"INSERT INTO {table} ({columns}) VALUES ({marks})"

        if returning is None:
            self.execute(statement, params)
            return None
        if self.dialect == POSTGRES:
            cur = self.execute(f"{statement} RETURNING {returning}", params)
            return int(cur.fetchone()[returning])
        cur = self.execute(statement, params)
        return int(cur.lastrowid)

    def insert_ignore_many(self, table: str, columns: list[str], rows) -> int:
        """Insert rows, skipping any that collide. Returns how many landed.

        This is how inventory is taken off sale: nights that are already spoken
        for must be left exactly as they are, never overwritten.
        """
        rows = [tuple(row) for row in rows]
        if not rows:
            return 0
        names = ", ".join(columns)
        marks = ", ".join("?" * len(columns))

        if self.dialect == POSTGRES:
            cur = self.raw.cursor()
            cur.executemany(
                self.sql(f"INSERT INTO {table} ({names}) VALUES ({marks})"
                         f" ON CONFLICT DO NOTHING"), rows)
            return max(cur.rowcount or 0, 0)
        cur = self.raw.executemany(
            f"INSERT OR IGNORE INTO {table} ({names}) VALUES ({marks})", rows)
        return max(cur.rowcount or 0, 0)

    def upsert(self, table: str, values: dict, *, key: str) -> None:
        """Insert a row, replacing any existing one with the same key."""
        columns = ", ".join(values)
        marks = ", ".join("?" * len(values))
        params = tuple(values.values())

        if self.dialect == POSTGRES:
            assignments = ", ".join(
                f"{column} = EXCLUDED.{column}" for column in values if column != key)
            self.execute(
                f"INSERT INTO {table} ({columns}) VALUES ({marks})"
                f" ON CONFLICT ({key}) DO UPDATE SET {assignments}", params)
        else:
            self.execute(
                f"INSERT OR REPLACE INTO {table} ({columns}) VALUES ({marks})", params)

    def lock_room(self, room_id: int) -> None:
        """Serialise writes for one room.

        SQLite's ``BEGIN IMMEDIATE`` already takes a database-wide write lock,
        so this is only needed on PostgreSQL, where an advisory lock reproduces
        the same guarantee at room granularity: two reservations for the same
        room queue up instead of racing, and the loser gets a clean "not
        available" rather than a constraint violation. The lock is released
        when the transaction ends, however it ends.
        """
        if self.dialect == POSTGRES:
            self.execute("SELECT pg_advisory_xact_lock(?)", (int(room_id),))

    # -- transactions ---------------------------------------------------------

    def begin(self) -> None:
        self.execute("BEGIN IMMEDIATE" if self.dialect == SQLITE else "BEGIN")

    def commit_tx(self) -> None:
        self.execute("COMMIT")

    def rollback_tx(self) -> None:
        self.execute("ROLLBACK")

    # -- lifecycle ------------------------------------------------------------

    def commit(self) -> None:
        try:
            self.raw.commit()
        except Exception:                      # autocommit connections
            pass

    def close(self) -> None:
        self.raw.close()


class _Empty:
    """Stands in for a cursor when there was nothing to do."""

    rowcount = 0

    def fetchone(self):
        return None

    def fetchall(self):
        return []

    def __iter__(self):
        return iter(())


# ---------------------------------------------------------------------------
# Opening a connection
# ---------------------------------------------------------------------------

def connect(url: str | Path = "perch.db") -> Database:
    dialect = dialect_of(url)
    if dialect == POSTGRES:
        return _connect_postgres(str(url))
    return _connect_sqlite(url)


def _dict_row(cursor, row):
    """Return rows as plain dicts on SQLite too.

    ``sqlite3.Row`` iterates over its *values* while a dict iterates over its
    *keys*, so any code that iterates a row behaves differently on the two
    backends.  Normalising here means the ledger and sync engine cannot depend
    on a row type at all.
    """
    return {column[0]: value for column, value in zip(cursor.description, row)}


def _connect_sqlite(path: str | Path) -> Database:
    conn = sqlite3.connect(str(path), isolation_level=None, timeout=15.0)
    conn.row_factory = _dict_row
    conn.execute("PRAGMA foreign_keys = ON")
    conn.execute("PRAGMA busy_timeout = 15000")
    try:
        conn.execute("PRAGMA journal_mode = WAL")
    except sqlite3.DatabaseError:              # :memory: and some filesystems
        pass
    return Database(conn, SQLITE)


def _connect_postgres(url: str) -> Database:
    import psycopg
    from psycopg.rows import dict_row

    # Supabase hands out a URL with a ``postgresql+psycopg://`` prefix in some
    # of its copy-paste snippets; psycopg wants the plain scheme.
    url = url.replace("postgresql+psycopg://", "postgresql://")

    # autocommit=True so this layer drives BEGIN/COMMIT explicitly, matching
    # how the SQLite side behaves — every write path is an explicit transaction.
    conn = psycopg.connect(url, autocommit=True, row_factory=dict_row,
                           connect_timeout=15)
    return Database(conn, POSTGRES)


def describe(url: str | Path) -> str:
    """A human-readable label for logs and the health endpoint — never the
    password, which a connection string always carries."""
    if dialect_of(url) == SQLITE:
        return f"SQLite file: {url}"
    parsed = urlparse(str(url).replace("postgresql+psycopg://", "postgresql://"))
    return f"PostgreSQL: {parsed.hostname}/{(parsed.path or '/').lstrip('/')}"
